// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetReservationOperation     OperationName = "GetReservation"
	GetReservationInfoOperation OperationName = "GetReservationInfo"
	GetTrainInfoOperation       OperationName = "GetTrainInfo"
	PatchReservationOperation   OperationName = "PatchReservation"
	PostReservationOperation    OperationName = "PostReservation"
)
