// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTrainInfoTimeTable returns new OptTrainInfoTimeTable with value set to v.
func NewOptTrainInfoTimeTable(v TrainInfoTimeTable) OptTrainInfoTimeTable {
	return OptTrainInfoTimeTable{
		Value: v,
		Set:   true,
	}
}

// OptTrainInfoTimeTable is optional TrainInfoTimeTable.
type OptTrainInfoTimeTable struct {
	Value TrainInfoTimeTable
	Set   bool
}

// IsSet returns true if OptTrainInfoTimeTable was set.
func (o OptTrainInfoTimeTable) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTrainInfoTimeTable) Reset() {
	var v TrainInfoTimeTable
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTrainInfoTimeTable) SetTo(v TrainInfoTimeTable) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTrainInfoTimeTable) Get() (v TrainInfoTimeTable, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTrainInfoTimeTable) Or(d TrainInfoTimeTable) TrainInfoTimeTable {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/trainInfo
type TrainInfo struct {
	// 列車番号.
	TrainNumber OptString `json:"trainNumber"`
	// 時刻表.
	TimeTable OptTrainInfoTimeTable `json:"timeTable"`
}

// GetTrainNumber returns the value of TrainNumber.
func (s *TrainInfo) GetTrainNumber() OptString {
	return s.TrainNumber
}

// GetTimeTable returns the value of TimeTable.
func (s *TrainInfo) GetTimeTable() OptTrainInfoTimeTable {
	return s.TimeTable
}

// SetTrainNumber sets the value of TrainNumber.
func (s *TrainInfo) SetTrainNumber(val OptString) {
	s.TrainNumber = val
}

// SetTimeTable sets the value of TimeTable.
func (s *TrainInfo) SetTimeTable(val OptTrainInfoTimeTable) {
	s.TimeTable = val
}

// 時刻表.
type TrainInfoTimeTable map[string]TrainInfoTimeTableItem

func (s *TrainInfoTimeTable) init() TrainInfoTimeTable {
	m := *s
	if m == nil {
		m = map[string]TrainInfoTimeTableItem{}
		*s = m
	}
	return m
}

type TrainInfoTimeTableItem struct {
	Code OptString   `json:"code"`
	Text OptDateTime `json:"text"`
}

// GetCode returns the value of Code.
func (s *TrainInfoTimeTableItem) GetCode() OptString {
	return s.Code
}

// GetText returns the value of Text.
func (s *TrainInfoTimeTableItem) GetText() OptDateTime {
	return s.Text
}

// SetCode sets the value of Code.
func (s *TrainInfoTimeTableItem) SetCode(val OptString) {
	s.Code = val
}

// SetText sets the value of Text.
func (s *TrainInfoTimeTableItem) SetText(val OptDateTime) {
	s.Text = val
}
