// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTrainInfoTimeTbale returns new OptTrainInfoTimeTbale with value set to v.
func NewOptTrainInfoTimeTbale(v TrainInfoTimeTbale) OptTrainInfoTimeTbale {
	return OptTrainInfoTimeTbale{
		Value: v,
		Set:   true,
	}
}

// OptTrainInfoTimeTbale is optional TrainInfoTimeTbale.
type OptTrainInfoTimeTbale struct {
	Value TrainInfoTimeTbale
	Set   bool
}

// IsSet returns true if OptTrainInfoTimeTbale was set.
func (o OptTrainInfoTimeTbale) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTrainInfoTimeTbale) Reset() {
	var v TrainInfoTimeTbale
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTrainInfoTimeTbale) SetTo(v TrainInfoTimeTbale) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTrainInfoTimeTbale) Get() (v TrainInfoTimeTbale, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTrainInfoTimeTbale) Or(d TrainInfoTimeTbale) TrainInfoTimeTbale {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/trainInfo
type TrainInfo struct {
	// 列車番号.
	TrainNumber OptString `json:"trainNumber"`
	// 時刻表.
	TimeTbale OptTrainInfoTimeTbale `json:"timeTbale"`
}

// GetTrainNumber returns the value of TrainNumber.
func (s *TrainInfo) GetTrainNumber() OptString {
	return s.TrainNumber
}

// GetTimeTbale returns the value of TimeTbale.
func (s *TrainInfo) GetTimeTbale() OptTrainInfoTimeTbale {
	return s.TimeTbale
}

// SetTrainNumber sets the value of TrainNumber.
func (s *TrainInfo) SetTrainNumber(val OptString) {
	s.TrainNumber = val
}

// SetTimeTbale sets the value of TimeTbale.
func (s *TrainInfo) SetTimeTbale(val OptTrainInfoTimeTbale) {
	s.TimeTbale = val
}

// 時刻表.
type TrainInfoTimeTbale map[string]TrainInfoTimeTbaleItem

func (s *TrainInfoTimeTbale) init() TrainInfoTimeTbale {
	m := *s
	if m == nil {
		m = map[string]TrainInfoTimeTbaleItem{}
		*s = m
	}
	return m
}

type TrainInfoTimeTbaleItem struct {
	Code OptString   `json:"code"`
	Text OptDateTime `json:"text"`
}

// GetCode returns the value of Code.
func (s *TrainInfoTimeTbaleItem) GetCode() OptString {
	return s.Code
}

// GetText returns the value of Text.
func (s *TrainInfoTimeTbaleItem) GetText() OptDateTime {
	return s.Text
}

// SetCode sets the value of Code.
func (s *TrainInfoTimeTbaleItem) SetCode(val OptString) {
	s.Code = val
}

// SetText sets the value of Text.
func (s *TrainInfoTimeTbaleItem) SetText(val OptDateTime) {
	s.Text = val
}
