// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// 座席番号をキーとした予約状況のマップ.
type GetReservationSeatOK map[string]GetReservationSeatOKItem

func (s *GetReservationSeatOK) init() GetReservationSeatOK {
	m := *s
	if m == nil {
		m = map[string]GetReservationSeatOKItem{}
		*s = m
	}
	return m
}

type GetReservationSeatOKItem struct {
	SeatNumber string `json:"seatNumber"`
	Status     bool   `json:"status"`
}

// GetSeatNumber returns the value of SeatNumber.
func (s *GetReservationSeatOKItem) GetSeatNumber() string {
	return s.SeatNumber
}

// GetStatus returns the value of Status.
func (s *GetReservationSeatOKItem) GetStatus() bool {
	return s.Status
}

// SetSeatNumber sets the value of SeatNumber.
func (s *GetReservationSeatOKItem) SetSeatNumber(val string) {
	s.SeatNumber = val
}

// SetStatus sets the value of Status.
func (s *GetReservationSeatOKItem) SetStatus(val bool) {
	s.Status = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPatchReservationReqReservationStatus returns new OptPatchReservationReqReservationStatus with value set to v.
func NewOptPatchReservationReqReservationStatus(v PatchReservationReqReservationStatus) OptPatchReservationReqReservationStatus {
	return OptPatchReservationReqReservationStatus{
		Value: v,
		Set:   true,
	}
}

// OptPatchReservationReqReservationStatus is optional PatchReservationReqReservationStatus.
type OptPatchReservationReqReservationStatus struct {
	Value PatchReservationReqReservationStatus
	Set   bool
}

// IsSet returns true if OptPatchReservationReqReservationStatus was set.
func (o OptPatchReservationReqReservationStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPatchReservationReqReservationStatus) Reset() {
	var v PatchReservationReqReservationStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPatchReservationReqReservationStatus) SetTo(v PatchReservationReqReservationStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPatchReservationReqReservationStatus) Get() (v PatchReservationReqReservationStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPatchReservationReqReservationStatus) Or(d PatchReservationReqReservationStatus) PatchReservationReqReservationStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReservationInfoReservationStatus returns new OptReservationInfoReservationStatus with value set to v.
func NewOptReservationInfoReservationStatus(v ReservationInfoReservationStatus) OptReservationInfoReservationStatus {
	return OptReservationInfoReservationStatus{
		Value: v,
		Set:   true,
	}
}

// OptReservationInfoReservationStatus is optional ReservationInfoReservationStatus.
type OptReservationInfoReservationStatus struct {
	Value ReservationInfoReservationStatus
	Set   bool
}

// IsSet returns true if OptReservationInfoReservationStatus was set.
func (o OptReservationInfoReservationStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReservationInfoReservationStatus) Reset() {
	var v ReservationInfoReservationStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReservationInfoReservationStatus) SetTo(v ReservationInfoReservationStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReservationInfoReservationStatus) Get() (v ReservationInfoReservationStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReservationInfoReservationStatus) Or(d ReservationInfoReservationStatus) ReservationInfoReservationStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PatchReservationOK is response for PatchReservation operation.
type PatchReservationOK struct{}

type PatchReservationReq struct {
	// 予約列車番号.
	ReservationTrainNumber OptInt `json:"reservationTrainNumber"`
	// 乗車駅.
	BoardingStation OptString `json:"boardingStation"`
	// 降車駅.
	GetOffStation OptString `json:"getOffStation"`
	// 予約席.
	ReservationSeatList []string `json:"reservationSeatList"`
	// 予約人数.
	ReservationPeople OptInt `json:"reservationPeople"`
	// 予約状況.
	ReservationStatus OptPatchReservationReqReservationStatus `json:"reservationStatus"`
	// 顧客情報.
	CustomerInfo OptString `json:"customerInfo"`
}

// GetReservationTrainNumber returns the value of ReservationTrainNumber.
func (s *PatchReservationReq) GetReservationTrainNumber() OptInt {
	return s.ReservationTrainNumber
}

// GetBoardingStation returns the value of BoardingStation.
func (s *PatchReservationReq) GetBoardingStation() OptString {
	return s.BoardingStation
}

// GetGetOffStation returns the value of GetOffStation.
func (s *PatchReservationReq) GetGetOffStation() OptString {
	return s.GetOffStation
}

// GetReservationSeatList returns the value of ReservationSeatList.
func (s *PatchReservationReq) GetReservationSeatList() []string {
	return s.ReservationSeatList
}

// GetReservationPeople returns the value of ReservationPeople.
func (s *PatchReservationReq) GetReservationPeople() OptInt {
	return s.ReservationPeople
}

// GetReservationStatus returns the value of ReservationStatus.
func (s *PatchReservationReq) GetReservationStatus() OptPatchReservationReqReservationStatus {
	return s.ReservationStatus
}

// GetCustomerInfo returns the value of CustomerInfo.
func (s *PatchReservationReq) GetCustomerInfo() OptString {
	return s.CustomerInfo
}

// SetReservationTrainNumber sets the value of ReservationTrainNumber.
func (s *PatchReservationReq) SetReservationTrainNumber(val OptInt) {
	s.ReservationTrainNumber = val
}

// SetBoardingStation sets the value of BoardingStation.
func (s *PatchReservationReq) SetBoardingStation(val OptString) {
	s.BoardingStation = val
}

// SetGetOffStation sets the value of GetOffStation.
func (s *PatchReservationReq) SetGetOffStation(val OptString) {
	s.GetOffStation = val
}

// SetReservationSeatList sets the value of ReservationSeatList.
func (s *PatchReservationReq) SetReservationSeatList(val []string) {
	s.ReservationSeatList = val
}

// SetReservationPeople sets the value of ReservationPeople.
func (s *PatchReservationReq) SetReservationPeople(val OptInt) {
	s.ReservationPeople = val
}

// SetReservationStatus sets the value of ReservationStatus.
func (s *PatchReservationReq) SetReservationStatus(val OptPatchReservationReqReservationStatus) {
	s.ReservationStatus = val
}

// SetCustomerInfo sets the value of CustomerInfo.
func (s *PatchReservationReq) SetCustomerInfo(val OptString) {
	s.CustomerInfo = val
}

// 予約状況.
type PatchReservationReqReservationStatus string

const (
	PatchReservationReqReservationStatusRESERVED    PatchReservationReqReservationStatus = "RESERVED"
	PatchReservationReqReservationStatusPROVISIONAL PatchReservationReqReservationStatus = "PROVISIONAL"
	PatchReservationReqReservationStatusCANCELLED   PatchReservationReqReservationStatus = "CANCELLED"
)

// AllValues returns all PatchReservationReqReservationStatus values.
func (PatchReservationReqReservationStatus) AllValues() []PatchReservationReqReservationStatus {
	return []PatchReservationReqReservationStatus{
		PatchReservationReqReservationStatusRESERVED,
		PatchReservationReqReservationStatusPROVISIONAL,
		PatchReservationReqReservationStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PatchReservationReqReservationStatus) MarshalText() ([]byte, error) {
	switch s {
	case PatchReservationReqReservationStatusRESERVED:
		return []byte(s), nil
	case PatchReservationReqReservationStatusPROVISIONAL:
		return []byte(s), nil
	case PatchReservationReqReservationStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PatchReservationReqReservationStatus) UnmarshalText(data []byte) error {
	switch PatchReservationReqReservationStatus(data) {
	case PatchReservationReqReservationStatusRESERVED:
		*s = PatchReservationReqReservationStatusRESERVED
		return nil
	case PatchReservationReqReservationStatusPROVISIONAL:
		*s = PatchReservationReqReservationStatusPROVISIONAL
		return nil
	case PatchReservationReqReservationStatusCANCELLED:
		*s = PatchReservationReqReservationStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// PostReservationOK is response for PostReservation operation.
type PostReservationOK struct{}

type PostReservationReq struct {
	// 予約列車番号.
	ReservationTrainNumber int `json:"reservationTrainNumber"`
	// 乗車駅.
	BoardingStation string `json:"boardingStation"`
	// 降車駅.
	GetOffStation string `json:"getOffStation"`
	// 予約席.
	ReservationSeatList []string `json:"reservationSeatList"`
	// 予約人数.
	ReservationPeople int `json:"reservationPeople"`
	// 顧客情報.
	CustomerInfo string `json:"customerInfo"`
}

// GetReservationTrainNumber returns the value of ReservationTrainNumber.
func (s *PostReservationReq) GetReservationTrainNumber() int {
	return s.ReservationTrainNumber
}

// GetBoardingStation returns the value of BoardingStation.
func (s *PostReservationReq) GetBoardingStation() string {
	return s.BoardingStation
}

// GetGetOffStation returns the value of GetOffStation.
func (s *PostReservationReq) GetGetOffStation() string {
	return s.GetOffStation
}

// GetReservationSeatList returns the value of ReservationSeatList.
func (s *PostReservationReq) GetReservationSeatList() []string {
	return s.ReservationSeatList
}

// GetReservationPeople returns the value of ReservationPeople.
func (s *PostReservationReq) GetReservationPeople() int {
	return s.ReservationPeople
}

// GetCustomerInfo returns the value of CustomerInfo.
func (s *PostReservationReq) GetCustomerInfo() string {
	return s.CustomerInfo
}

// SetReservationTrainNumber sets the value of ReservationTrainNumber.
func (s *PostReservationReq) SetReservationTrainNumber(val int) {
	s.ReservationTrainNumber = val
}

// SetBoardingStation sets the value of BoardingStation.
func (s *PostReservationReq) SetBoardingStation(val string) {
	s.BoardingStation = val
}

// SetGetOffStation sets the value of GetOffStation.
func (s *PostReservationReq) SetGetOffStation(val string) {
	s.GetOffStation = val
}

// SetReservationSeatList sets the value of ReservationSeatList.
func (s *PostReservationReq) SetReservationSeatList(val []string) {
	s.ReservationSeatList = val
}

// SetReservationPeople sets the value of ReservationPeople.
func (s *PostReservationReq) SetReservationPeople(val int) {
	s.ReservationPeople = val
}

// SetCustomerInfo sets the value of CustomerInfo.
func (s *PostReservationReq) SetCustomerInfo(val string) {
	s.CustomerInfo = val
}

// Ref: #/components/schemas/reservationInfo
type ReservationInfo struct {
	// 予約番号.
	ReservationNumber OptInt `json:"reservationNumber"`
	// 予約列車番号.
	ReservationTrainNumber OptInt `json:"reservationTrainNumber"`
	// 乗車駅.
	BoardingStation OptString `json:"boardingStation"`
	// 降車駅.
	GetOffStation OptString `json:"getOffStation"`
	// 予約席.
	ReservationSeatList []string `json:"reservationSeatList"`
	// 料金.
	Amount OptInt `json:"amount"`
	// 予約人数.
	ReservationPeople OptInt `json:"reservationPeople"`
	// 予約状況.
	ReservationStatus OptReservationInfoReservationStatus `json:"reservationStatus"`
	// 顧客情報.
	CustomerInfo OptString `json:"customerInfo"`
}

// GetReservationNumber returns the value of ReservationNumber.
func (s *ReservationInfo) GetReservationNumber() OptInt {
	return s.ReservationNumber
}

// GetReservationTrainNumber returns the value of ReservationTrainNumber.
func (s *ReservationInfo) GetReservationTrainNumber() OptInt {
	return s.ReservationTrainNumber
}

// GetBoardingStation returns the value of BoardingStation.
func (s *ReservationInfo) GetBoardingStation() OptString {
	return s.BoardingStation
}

// GetGetOffStation returns the value of GetOffStation.
func (s *ReservationInfo) GetGetOffStation() OptString {
	return s.GetOffStation
}

// GetReservationSeatList returns the value of ReservationSeatList.
func (s *ReservationInfo) GetReservationSeatList() []string {
	return s.ReservationSeatList
}

// GetAmount returns the value of Amount.
func (s *ReservationInfo) GetAmount() OptInt {
	return s.Amount
}

// GetReservationPeople returns the value of ReservationPeople.
func (s *ReservationInfo) GetReservationPeople() OptInt {
	return s.ReservationPeople
}

// GetReservationStatus returns the value of ReservationStatus.
func (s *ReservationInfo) GetReservationStatus() OptReservationInfoReservationStatus {
	return s.ReservationStatus
}

// GetCustomerInfo returns the value of CustomerInfo.
func (s *ReservationInfo) GetCustomerInfo() OptString {
	return s.CustomerInfo
}

// SetReservationNumber sets the value of ReservationNumber.
func (s *ReservationInfo) SetReservationNumber(val OptInt) {
	s.ReservationNumber = val
}

// SetReservationTrainNumber sets the value of ReservationTrainNumber.
func (s *ReservationInfo) SetReservationTrainNumber(val OptInt) {
	s.ReservationTrainNumber = val
}

// SetBoardingStation sets the value of BoardingStation.
func (s *ReservationInfo) SetBoardingStation(val OptString) {
	s.BoardingStation = val
}

// SetGetOffStation sets the value of GetOffStation.
func (s *ReservationInfo) SetGetOffStation(val OptString) {
	s.GetOffStation = val
}

// SetReservationSeatList sets the value of ReservationSeatList.
func (s *ReservationInfo) SetReservationSeatList(val []string) {
	s.ReservationSeatList = val
}

// SetAmount sets the value of Amount.
func (s *ReservationInfo) SetAmount(val OptInt) {
	s.Amount = val
}

// SetReservationPeople sets the value of ReservationPeople.
func (s *ReservationInfo) SetReservationPeople(val OptInt) {
	s.ReservationPeople = val
}

// SetReservationStatus sets the value of ReservationStatus.
func (s *ReservationInfo) SetReservationStatus(val OptReservationInfoReservationStatus) {
	s.ReservationStatus = val
}

// SetCustomerInfo sets the value of CustomerInfo.
func (s *ReservationInfo) SetCustomerInfo(val OptString) {
	s.CustomerInfo = val
}

// 予約状況.
type ReservationInfoReservationStatus string

const (
	ReservationInfoReservationStatusRESERVED    ReservationInfoReservationStatus = "RESERVED"
	ReservationInfoReservationStatusPROVISIONAL ReservationInfoReservationStatus = "PROVISIONAL"
	ReservationInfoReservationStatusCANCELLED   ReservationInfoReservationStatus = "CANCELLED"
)

// AllValues returns all ReservationInfoReservationStatus values.
func (ReservationInfoReservationStatus) AllValues() []ReservationInfoReservationStatus {
	return []ReservationInfoReservationStatus{
		ReservationInfoReservationStatusRESERVED,
		ReservationInfoReservationStatusPROVISIONAL,
		ReservationInfoReservationStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReservationInfoReservationStatus) MarshalText() ([]byte, error) {
	switch s {
	case ReservationInfoReservationStatusRESERVED:
		return []byte(s), nil
	case ReservationInfoReservationStatusPROVISIONAL:
		return []byte(s), nil
	case ReservationInfoReservationStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReservationInfoReservationStatus) UnmarshalText(data []byte) error {
	switch ReservationInfoReservationStatus(data) {
	case ReservationInfoReservationStatusRESERVED:
		*s = ReservationInfoReservationStatusRESERVED
		return nil
	case ReservationInfoReservationStatusPROVISIONAL:
		*s = ReservationInfoReservationStatusPROVISIONAL
		return nil
	case ReservationInfoReservationStatusCANCELLED:
		*s = ReservationInfoReservationStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/trainInfo
type TrainInfo struct {
	// 列車番号.
	TrainNumber OptInt `json:"trainNumber"`
	// 時刻表.
	TimeTable []TrainInfoTimeTableItem `json:"timeTable"`
}

// GetTrainNumber returns the value of TrainNumber.
func (s *TrainInfo) GetTrainNumber() OptInt {
	return s.TrainNumber
}

// GetTimeTable returns the value of TimeTable.
func (s *TrainInfo) GetTimeTable() []TrainInfoTimeTableItem {
	return s.TimeTable
}

// SetTrainNumber sets the value of TrainNumber.
func (s *TrainInfo) SetTrainNumber(val OptInt) {
	s.TrainNumber = val
}

// SetTimeTable sets the value of TimeTable.
func (s *TrainInfo) SetTimeTable(val []TrainInfoTimeTableItem) {
	s.TimeTable = val
}

type TrainInfoTimeTableItem struct {
	Station OptString   `json:"station"`
	Time    OptDateTime `json:"time"`
}

// GetStation returns the value of Station.
func (s *TrainInfoTimeTableItem) GetStation() OptString {
	return s.Station
}

// GetTime returns the value of Time.
func (s *TrainInfoTimeTableItem) GetTime() OptDateTime {
	return s.Time
}

// SetStation sets the value of Station.
func (s *TrainInfoTimeTableItem) SetStation(val OptString) {
	s.Station = val
}

// SetTime sets the value of Time.
func (s *TrainInfoTimeTableItem) SetTime(val OptDateTime) {
	s.Time = val
}
