// Code generated by ogen, DO NOT EDIT.

package presentation

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetReservationInfo implements getReservationInfo operation.
//
// 個別の予約情報取得.
//
// GET /reservations/{reservationNumber}
func (UnimplementedHandler) GetReservationInfo(ctx context.Context, params GetReservationInfoParams) (r *ReservationInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReservationSeat implements getReservationSeat operation.
//
// 号車ごとの予約状況取得.
//
// GET /reservationSeats
func (UnimplementedHandler) GetReservationSeat(ctx context.Context, params GetReservationSeatParams) (r GetReservationSeatOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrainInfo implements getTrainInfo operation.
//
// 列車情報の取得.
//
// GET /trains
func (UnimplementedHandler) GetTrainInfo(ctx context.Context, params GetTrainInfoParams) (r GetTrainInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchReservation implements patchReservation operation.
//
// 予約情報更新.
//
// PATCH /reservations/{reservationNumber}
func (UnimplementedHandler) PatchReservation(ctx context.Context, req *PatchReservationReq, params PatchReservationParams) error {
	return ht.ErrNotImplemented
}

// PostReservation implements postReservation operation.
//
// 予約情報の作成.
//
// POST /reservations
func (UnimplementedHandler) PostReservation(ctx context.Context, req *PostReservationReq) error {
	return ht.ErrNotImplemented
}
