// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
)

// GetTrainInfoParams is parameters of getTrainInfo operation.
type GetTrainInfoParams struct {
	// 列車情報.
	TrainNumber string
}

func unpackGetTrainInfoParams(packed middleware.Parameters) (params GetTrainInfoParams) {
	{
		key := middleware.ParameterKey{
			Name: "trainNumber",
			In:   "path",
		}
		params.TrainNumber = packed[key].(string)
	}
	return params
}

func decodeGetTrainInfoParams(args [0]string, argsEscaped bool, r *http.Request) (params GetTrainInfoParams, _ error) {
	// Decode path: trainNumber.
	if err := func() error {
		// Not used.
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "trainNumber",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
