// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetTrainInfo implements getTrainInfo operation.
//
// 列車情報の取得.
//
// GET /train/{trainNumber}
func (UnimplementedHandler) GetTrainInfo(ctx context.Context, params GetTrainInfoParams) (r *TrainInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// PostReservation implements postReservation operation.
//
// 予約情報の作成.
//
// POST /reservation
func (UnimplementedHandler) PostReservation(ctx context.Context, req *PostReservationReq) error {
	return ht.ErrNotImplemented
}
