// Code generated by ogen, DO NOT EDIT.

package presentation

// OperationName is the ogen operation name
type OperationName = string

const (
	GetReservationInfoOperation OperationName = "GetReservationInfo"
	GetReservationSeatOperation OperationName = "GetReservationSeat"
	GetTrainInfoOperation       OperationName = "GetTrainInfo"
	PatchReservationOperation   OperationName = "PatchReservation"
	PostReservationOperation    OperationName = "PostReservation"
)
